## Aliases
alias vim=nvim

## Keybindings
bindkey '\t' forward-word

## Colors
export CLICOLOR=1

## Hooks 
precmd () {
  echo -en "\033]0;$(basename `pwd`)\a"

  if grep -q Microsoft /proc/version; then
    printf "\033]7;file://%s\033\\" $(wslpath -w "$PWD") 
  fi
}

## Autocomplete
source ~/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

