## Core
autoload -Uz promptinit
promptinit
prompt adam1 

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
kHISTSIZE=1000

## Aliases
alias vim=nvim

## Keybindings
bindkey '\t' forward-word

## Hooks 
precmd () {
  if grep -q Microsoft /proc/version; then
    printf "\033]7;file://%s\033\\" $(wslpath -w "$PWD") 
  fi
}

## Autocomplete
source ~/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

